export const REQUEST_MAPS_TYPES_START = '[Maps] REQUEST_MAPS_TYPES_START';
export const REQUEST_MAPS_TYPES_SUCCESS = '[Maps] REQUEST_MAPS_TYPES_SUCCESS';
export const REQUEST_MAPS_TYPES_ERROR = '[Maps] REQUEST_MAPS_TYPES_ERROR';
